export const brandsList = [
  { name: 'xiaomi', title: 'شیائومی ' },
  { name: 'taomicmic', title: 'تائومیک میک' },
  { name: 'xo', title: 'ایکس او ' },
  { name: 'coteetci', title: 'کوتتسی ' },
  { name: 'earldom', title: 'ارلدام ' },
  { name: 'baseus', title: 'بیسوس ' },
  { name: 'green', title: 'گرین Green' },
  { name: 'smilingshark', title: 'اسمایلینگ شارک ' },
  { name: 'proone', title: 'پرووان ' },
  { name: 'powerology', title: 'پاورولوژی ' },
  { name: 'sothing', title: 'سوتینگ ' },
  { name: 'porodo', title: 'پورودو ' },
  { name: 'ugreen', title: 'یوگرین ' },
  { name: 'skg', title: 'اس کا جی ' },
  { name: 'ldnio', title: 'الدنیو ' },
  { name: 'bange', title: 'بنج ' },
  { name: 'remax', title: 'ریمکس ' },
  { name: 'recci', title: 'رسی ' },
  { name: 'hadron', title: 'هادرون ' },
  { name: 'usams', title: 'یوسامز ' },
  { name: 'mcdodo', title: 'مک دودو ' },
  { name: 'wiwu', title: 'ویوو ' },
  { name: 'kemei', title: 'کمی ' },
  { name: 'tamclean', title: 'تام کلین ' },
  { name: 'joyroom', title: 'جویروم ' },
  { name: 'qcy', title: 'کیو سی وای ' },
  { name: 'anker', title: 'انکر ' },
  { name: 'sunicety', title: 'سانی ستی ' },
  { name: 'ahastyle', title: 'آها استایل ' },
  { name: 'zhuse', title: 'ژوس ' },
  { name: 'samsung', title: 'سامسونگ ' },
  { name: 'orico', title: 'اوریکو ' },
  { name: 'apple', title: 'اپل ' },
  { name: 'totu', title: 'توتو ' },
  { name: 'rock', title: 'راک ' },
  { name: 'creative', title: 'کریتیو ' },
  { name: 'lenovo', title: 'لنوو ' },
  { name: 'momax', title: 'مومکس ' },
  { name: 'nillkin', title: 'نیلکین ' },
  { name: 'hoco', title: 'هوکو ' },
  { name: 'yoobao', title: 'یوبائو ' },
  { name: 'aukey', title: 'آکی ' },
  { name: 'ipega', title: 'آیپگا ' },
  { name: 'apacer', title: 'اپیسر ' },
  { name: 'hp', title: 'اچ پی ' },
  { name: 'adonet', title: 'ادونیت ' },
  { name: 'spigen', title: 'اسپیگن ' },
  { name: 'stoptime', title: 'استوپ تایم ' },
  { name: 'sphero', title: 'اسفیرو ' },
  { name: 'smiger', title: 'اسمایگر ' },
  { name: 'axpro', title: 'اکسپرو ' },
  { name: 'lg', title: 'ال جی ' },
  { name: 'lcdarm', title: 'ال سی دی آرم ' },
  { name: 'elago', title: 'الاگو ' },
  { name: 'energea', title: 'انرجیا ' },
  { name: 'ozaki', title: 'اوزاکی ' },
  { name: 'adata', title: 'ای دیتا ' },
  { name: 'asus', title: 'ایسوس ' },
  { name: 'bopmen', title: 'باپمن ' },
  { name: 'bafo', title: 'بافو ' },
  { name: 'bavin', title: 'باوین ' },
  { name: 'belkin', title: 'بلکین ' },
  { name: 'bose', title: 'بوز ' },
  { name: 'boya', title: 'بویا ' },
  { name: 'beats', title: 'بیتس ' },
  { name: 'panasonic', title: 'پاناسونیک ' },
  { name: 'promate', title: 'پرومیت ' },
  { name: 'plantronics', title: 'پلنترونیکس ' },
  { name: 'poso', title: 'پوسو ' },
  { name: 'polo', title: 'پولو ' },
  { name: 'transcend', title: 'ترنسند ' },
  { name: 'treatanex', title: 'تریتانکس ' },
  { name: 'tsco', title: 'تسکو ' },
  { name: 'tplink', title: 'تی پی لینک ' },
  { name: 'jabra', title: 'جبرا ' },
  { name: 'joway', title: 'جووی ' },
  { name: 'jbl', title: 'جی بی ال ' },
  { name: 'jmary', title: 'جی ماری ' },
  { name: 'wking', title: 'دبلیو کینگ' },
  { name: 'devia', title: 'دویا ' },
  { name: 'dji', title: 'دی جی آی ' },
  { name: 'dlink', title: 'دی لینک ' },
  { name: 'romoss', title: 'روموس ' },
  { name: 'sonpre', title: 'سانپری ' },
  { name: 'sandisk', title: 'سندیسک ' },
  { name: 'sony', title: 'سونی ' },
  { name: 'cgmobile', title: 'سی‌جی موبایل  ' },
  { name: 'siliconpower', title: 'سیلیکون پاور  ' },
  { name: 'farassoo', title: 'فراسو ' },
  { name: 'philips', title: 'فیلیپس ' },
  { name: 'kaku', title: 'کاکو ' },
  { name: 'konfulon', title: 'کانفلون ' },
  { name: 'coolbell', title: 'کول بل ' },
  { name: 'gaolema', title: 'گوالما ' },
  { name: 'logitech', title: 'لاجیتک ' },
  { name: 'libratone', title: 'لیبراتون ' },
  { name: 'lito', title: 'لیتو ' },
  { name: 'lingting', title: 'لینگ تینگ ' },
  { name: 'mipow', title: 'مایپو ' },
  { name: 'motorola', title: 'موتورولا ' },
  { name: 'musicangel', title: 'موزیک انجل  ' },
  { name: 'moshi', title: 'موشی ' },
  { name: 'mifo', title: 'میفو ' },
  { name: 'nokia', title: 'نوکیا ' },
  { name: '1more', title: 'وان مور ' },
  { name: 'voltage', title: 'ولتاژ ' },
  { name: 'wiso', title: 'ویزو ' },
  { name: 'viccoman', title: 'ویکومن ' },
  { name: 'vivamadrid', title: 'ویوا مادرید  ' },
  { name: 'harmankardon', title: 'هارمن کاردن  ' },
  { name: 'haylou', title: 'هایلو ' },
  { name: 'huawei', title: 'هوآوی ' },
  { name: 'havit', title: 'هویت ' },
  { name: 'xundd', title: 'یاندو ' },
  { name: 'yesido', title: 'یسیدو ' },
  { name: 'uniqueleaf', title: 'یونیک لیف ' },
];
